name: Docker Image CICD

on:
# Manual trigger
  workflow_dispatch:
    branches: [ "main" ]
jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install pylint
        run: pip install pylint
      - name: Linter
        run: cd classifier-app && pylint .
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: tag=$(date +%s) && docker build ./classifier-app/app --file classifier-app/app/docker/app/Dockerfile --tag comments-classifier:$tag --tag comments-classifier:latest
    - name: Test
      run: docker run -it comments-classifier:latest pytest
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: docker push comments-classifier:latest
