name: Lint check/ Code quality

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install pylint
        run: pip install pylint
      - name: Linter
        run: cd classifier-app && pylint .
